version: '2'
services:
    pcms-app:
        image: pcms
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://pcms-mysql:3306/pcms?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pcms-mysql:
        extends:
            file: mysql.yml
            service: pcms-mysql
